-- MySQL Script generated by MySQL Workbench
-- Mon Mar 28 23:12:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maine` DEFAULT CHARACTER SET utf8mb4 ;
USE `maine` ;

-- -----------------------------------------------------
-- Table `maine`.`maine_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_user` (
  `id` BIGINT UNSIGNED NOT NULL COMMENT '业务ID',
  `name` VARCHAR(16) NOT NULL COMMENT '用户名',
  `password` CHAR(128) NOT NULL COMMENT '密码',
  `password_status` TINYINT UNSIGNED NOT NULL COMMENT '密码状态\n\n0: 未设置密码\n1: 已设置密码\n',
  `phone` VARCHAR(16) NOT NULL COMMENT '手机号',
  `phone_status` TINYINT UNSIGNED NOT NULL COMMENT '手机号状态\n\n0: 未验证\n1: 已验证',
  `email` VARCHAR(32) NOT NULL COMMENT '邮箱',
  `email_status` TINYINT UNSIGNED NOT NULL COMMENT '邮箱状态\n\n0: 未验证\n1: 已验证',
  `status` TINYINT UNSIGNED NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maine`.`maine_attendance_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_attendance_record` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `serial_id` CHAR(36) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maine`.`maine_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_group` (
  `trace_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `status` TINYINT NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`trace_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `maine`.`maine_group_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_group_number` (
  `trace_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `group_id` BIGINT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`trace_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maine`.`maine_attendance_task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_attendance_task` (
  `trace_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `description` TEXT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `end_time` DATETIME NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`trace_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maine`.`maine_attendance_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_attendance_setting` (
  `task_id` BIGINT NOT NULL,
  `setting` BLOB NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maine`.`maine_attendance_task_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_attendance_task_code` (
  `trace_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` BIGINT UNSIGNED NOT NULL,
  `code` CHAR(6) NOT NULL,
  `expire_time` DATETIME NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`trace_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maine`.`maine_group_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_group_setting` (
  `trace_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` BIGINT UNSIGNED NOT NULL,
  `setting` BLOB NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`trace_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maine`.`maine_attendance_record_extend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maine`.`maine_attendance_record_extend` (
  `trace_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `record_id` BIGINT UNSIGNED NOT NULL,
  `info` BLOB NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`trace_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
